name: "Composite Action Test"

description: "Run multiple run steps"

inputs:
  your_name:
    description: 'Your name'
    default: 'Ethan'
  skip_step:
    description: 'skip step in composite action'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: step1
      run: echo Hi ${{ inputs.your_name }}
      if: inputs.skip_step
        
    - name: step2
      run: echo os ${{runner.os}}
      shell: bash
        
    - name: step3
      run: echo action step env.foo ${{ env.foo }}
      env: 
        foo: this is foo 2
      shell: bash
