name: "Composite Action Test"

description: "Run multiple run steps"

inputs:
  your_name:
    description: 'Your name'
    default: 'Ethan'
  skip_step:
    description: 'skip step in composite action'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: step1
      shell: bash
      run: echo Hi ${{ inputs.your_name }}
      if: ${{inputs.skip_step == 'true'}}
        
    - name: step2
      run: echo os ${{runner.os}}
      shell: bash